// src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link'; // Import Link for navigation
import { Button } from '@/components/ui/button'; // Import Button component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="flex justify-between items-center p-4 bg-gray-800 text-white">
          <h1 className="text-xl">UoA EventBuddy</h1>
          <Link href="/profile">
            <Button className="rounded-full p-3 bg-blue-500 text-white hover:bg-blue-600 transition">
              {/* Placeholder for profile icon */}
              <span>👤</span>
            </Button>
          </Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
